[general]
import = [
    "~/.config/alacritty/theme.toml"
]

[terminal]
[terminal.shell]
program = "zellij"

[window]
opacity = 0
padding = {x = 5, y = 10} 
decorations = "None"

[font]
size = 15

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.bold_italic]
family = "0xProto Nerd Font"
style = "Bold Italic"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = '\x1b\r'
